EKSCHENJ

⚡️EIn Barnaame Be Surat ee Yekpaarche Mibaawad Va Dar Aan Mitavaanid:

1. Hesaabdaari ye Burs Va Ramz Arz KHod Raa Anjaam Dahid.

2. Daaraaei ye Dijitaal TRX KHod Raa Dar Barnaame Negahdaari Konid Be Surat ee Offline, Ramz ee Daaraaei Be Surat ee Offline Va Encrypt Wod e (End-to-End) Zakhire Miwavad, Enteqaal Daaraaei Be Aadres ee Digar.

3. Negahdaari ye Ramz haaye Barnaame Va Site, Negahdaari ye Ramz haaye Vorud ee 2 Marhale-ei (RamzBiz Va RamzBiz-V2).

4. Feworde Saazi ye Tasaavir.

5. Saakht ee QrCode(RamzCode).

6. KHaandan ee QrCode(RamzCode).

7. Sabt ee Mahsulaat Va Aqlaam i Ke Daaraaye Taarikh ee Enqezaa Hastand Va Mavaared ee Digar...

---------------------------------------------------
EXCHANGE

⚡️This application is an all-in-one solution that allows you to:

1. Manage your stock market and cryptocurrency accounting.

2. Store your TRX digital assets in the application offline. Your asset passvord is also stored offline and encrypted using end-to-end encryption, and you can transfer your assets to another address.

3. Store passwords for applications and websites, and store two-factor authentication (2FA) login codes (RamzBiz and RamzBiz-V2).

4. Compress images.

5. Create QR Codes (RamzCode).

6. Scan and read QR Codes (RamzCode).

7. Register and manage products and other items that have an expiration date, along vith many other features...
---------------------------------------------------
Official Url (Url Rasmi): https://github.com/mohamadhasansalmaaniyaan72/Exchange
